### ISSUE TITLE
user cannot go back to previous page when on Rating page

### ISSUE THREAD

**Issue by rickywid** [projectunic0rn/mentorship-ui#246] opened 2018-12-20 22:15 UTC
You cant go back to a previous page once you've decided to mark a mentorship as Complete on the Mentorships page. The Ratings page shows but there is no way to cancel or go back.

**Comment by roymoran** [comment] 2018-12-26 15:57
@rickywid currently this is by design. Submitting a rating is required when a mentorship marked as complete.

**Closed** 2018-12-26 17:49 UTC
Labels: in progress, medium priority
